import type { Metadata } from "next";
import { Poppins, Teko } from "next/font/google";
import Header from "@/layout/Header";
import SocialBar from "@/layout/SocialBar";
import NewsletterBar from "@/layout/Newsletter";
import Footer from "@/layout/Footer";
import "../styles/index.scss"

const poppins = Poppins({ 
  subsets: ["latin"], 
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'], 
  style: ['normal', 'italic'],
  display: 'swap',
  variable: '--ff-body',
});

const teko = Teko({
  subsets: ['latin'],
  display: 'swap',
  variable: '--ff-display',
})

const metadata: Metadata = {
  title: {
    template: '%s | Urban Bites',
    default: 'Urban Bites',
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${teko.variable}`}>
      <Header />
      {children}
      <SocialBar />
      <NewsletterBar />
      <Footer />
    </body>
    </html>
  );
}